server:
  port: 8000

spring:
  datasource:
    #    url: jdbc:sqlite::resource:db/mofang.db
    url: jdbc:sqlite:db/mofang.db  #项目根目录下的db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  # 配置freemarker
  freemarker:
    settings:
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
    request-context-attribute: request
  #全是默认值
#    # 设置模板后缀名
#    suffix: .ftl
#
#    # 设置文档类型
#    content-type: text/html
#    # 设置页面编码格式
#    charset: UTF-8
#    # 设置页面缓存
#    cache: false
#    # 设置ftl文件路径
#    template-loader-path: classpath:/templates/

  #设定静态文件路径，js,css等
#  resources:
#     static-locations: classpath:/templates/,classpath:/static/